{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.certManager.issuerName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ionos-dns-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ionos-dns-operator.fullname" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ionos-dns-operator.labels" . | nindent 4 }}
spec:
  secretName: {{ include "ionos-dns-operator.fullname" . }}-webhook-cert
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  usages:
  - server auth
  - digital signature
  - key encipherment
  dnsNames:
  - {{ include "ionos-dns-operator.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "ionos-dns-operator.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ .Values.certManager.issuerName }}
{{- end }}
