{{- if and (not .Values.ionos.existingSecret) .Values.ionos.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ionos-dns-operator.fullname" . }}-ionos
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ionos-dns-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ .Values.ionos.apiKey | quote }}
{{- end }}
